name: Build and Push ML Docker Image to GHCR

on:
  push:
    branches: [feature]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image name
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/ml/mistral-chat:latest" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: docker build -t $IMAGE MLOps

      - name: Push Docker image to GHCR
        run: docker push $IMAGE